# Generated by Django 3.0.4 on 2020-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200409_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
