# Generated by Django 3.0.4 on 2020-04-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_post_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.TextField(blank=True, default='welcome.gif', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='welcome.gif', null=True, upload_to=''),
        ),
    ]
