# Generated by Django 3.0.4 on 2020-04-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200416_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, default='welcome.gif', null=True, upload_to=''),
        ),
    ]
